version: "3"
services:
  postgres:
    image: postgres:13.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  prisma:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    tty: true
    volumes:
      - ./prisma:/app
